# Generated by Django 3.2.14 on 2022-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guests',
            options={'verbose_name_plural': 'Guests'},
        ),
        migrations.AddField(
            model_name='guests',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
